package GUIpackage;

import entityClassesPackage.ProjectDetailsTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author erwin
 */
public class ProjectGUI extends javax.swing.JFrame {

    private int id;
    ProjectDetailsTable p;

    /**
     * Creates new form ProjectGUI
     */
    public ProjectGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        FrugalProjectPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("FrugalProjectPU2").createEntityManager();
        projectDetailsTableQuery = java.beans.Beans.isDesignTime() ? null : FrugalProjectPUEntityManager.createQuery("SELECT p FROM ProjectDetailsTable p");
        projectDetailsTableList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : projectDetailsTableQuery.getResultList();
        pMainProjectBanner = new javax.swing.JPanel();
        lMainProjectBanner = new javax.swing.JLabel();
        pAddNewProject = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pProjectTable = new javax.swing.JPanel();
        spProjectTable = new javax.swing.JScrollPane();
        tProjectTable = new javax.swing.JTable();
        lProjectTable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1248, 600));

        pMainProjectBanner.setBackground(new java.awt.Color(255, 255, 255));
        pMainProjectBanner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 4));
        pMainProjectBanner.setPreferredSize(new java.awt.Dimension(1248, 95));

        lMainProjectBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fil-3squares-02.jpg"))); // NOI18N
        lMainProjectBanner.setPreferredSize(new java.awt.Dimension(1248, 80));

        javax.swing.GroupLayout pMainProjectBannerLayout = new javax.swing.GroupLayout(pMainProjectBanner);
        pMainProjectBanner.setLayout(pMainProjectBannerLayout);
        pMainProjectBannerLayout.setHorizontalGroup(
            pMainProjectBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainProjectBannerLayout.createSequentialGroup()
                .addComponent(lMainProjectBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMainProjectBannerLayout.setVerticalGroup(
            pMainProjectBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainProjectBannerLayout.createSequentialGroup()
                .addComponent(lMainProjectBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pAddNewProject.setBackground(new java.awt.Color(255, 255, 255));
        pAddNewProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        pAddNewProject.setPreferredSize(new java.awt.Dimension(100, 100));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Add Project");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pAddNewProjectLayout = new javax.swing.GroupLayout(pAddNewProject);
        pAddNewProject.setLayout(pAddNewProjectLayout);
        pAddNewProjectLayout.setHorizontalGroup(
            pAddNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAddNewProjectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
        );
        pAddNewProjectLayout.setVerticalGroup(
            pAddNewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAddNewProjectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pProjectTable.setBackground(new java.awt.Color(255, 255, 255));
        pProjectTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        pProjectTable.setPreferredSize(new java.awt.Dimension(1248, 474));

        spProjectTable.setPreferredSize(new java.awt.Dimension(1230, 320));

        tProjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tProjectTable.setTableHeader(null);
        spProjectTable.setViewportView(tProjectTable);

        lProjectTable.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lProjectTable.setText("Projects");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, projectDetailsTableList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${projectId}"));
        columnBinding.setColumnName("Project Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${projectName}"));
        columnBinding.setColumnName("Project Name");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("GoTo UserGUI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pProjectTableLayout = new javax.swing.GroupLayout(pProjectTable);
        pProjectTable.setLayout(pProjectTableLayout);
        pProjectTableLayout.setHorizontalGroup(
            pProjectTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProjectTableLayout.createSequentialGroup()
                .addComponent(spProjectTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pProjectTableLayout.createSequentialGroup()
                .addGroup(pProjectTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pProjectTableLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lProjectTable, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pProjectTableLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pProjectTableLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pProjectTableLayout.setVerticalGroup(
            pProjectTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pProjectTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lProjectTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton2)
                .addGap(103, 103, 103)
                .addComponent(spProjectTable, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pMainProjectBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, Short.MAX_VALUE)
                    .addComponent(pProjectTable, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                    .addComponent(pAddNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE))
                .addGap(0, 2759, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pMainProjectBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pAddNewProject, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pProjectTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      AddProject ap = new AddProject();
      ap.setVisible(true);
      
      this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int cel = jTable1.getSelectedRow();
        int hd;
        hd = (int) jTable1.getValueAt(cel, 0);

        p.setProjectId(hd);
        UserGUI ug = new UserGUI(p);
        
        //ug.setProjectID(hd);
        //String projName = (String) jTable1.getValueAt(cel, 1);
        //ug.setProjectTitle(projName);
        
        ug.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        ListSelectionModel rowSM = jTable1.getSelectionModel();

        rowSM.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int cel = jTable1.getSelectedRow();

                int hd;
                hd = (int) jTable1.getValueAt(cel, 0);

                p = new ProjectDetailsTable();
                p.setProjectId(hd);
                UserGUI u = new UserGUI(p);
                
                u.setProjectID(hd);
                String projName = (String) jTable1.getValueAt(cel, 1);
                u.setProjectTitle(projName);
            }
        });
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager FrugalProjectPUEntityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lMainProjectBanner;
    private javax.swing.JLabel lProjectTable;
    private javax.swing.JPanel pAddNewProject;
    private javax.swing.JPanel pMainProjectBanner;
    private javax.swing.JPanel pProjectTable;
    private java.util.List<entityClassesPackage.ProjectDetailsTable> projectDetailsTableList;
    private javax.persistence.Query projectDetailsTableQuery;
    private javax.swing.JScrollPane spProjectTable;
    private javax.swing.JTable tProjectTable;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
