
package GUIpackage;


import entityClassesPackage.ProjectDetailsTable;
import entityClassesPackage.TaskTable;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import controllerpackage.Controller;
import java.awt.Color;
import javax.swing.*;

import entityClassesPackage.MemberDetailsTable;
import java.text.*;
import java.util.Date;
import java.util.*;

/**
 *
 * @author erwin samaniego
 */
public class UserGUI extends javax.swing.JFrame {

    private JTable jtableBudget; //budget table
    private Controller budgetTableController;
    private JTable jtableCommunications;
    private Controller communicationsTableController;
    
    private int itemSelectedBudgetID;
    private static int projectID;
    private static String projectName;
    
    private Controller controller;
    private ProjectDetailsTable projectObj;
    
    private List<MemberDetailsTable> memberDetails;
    
    /**
     * Creates new form UserGUI
     */
    public UserGUI() {
        //UIManager.put("TabbedPane.selected", Color.RED);
        
        initComponents();
        controller = new Controller();
        budgetTableController = new Controller();
        communicationsTableController = new Controller();
        
        //UIManager.put("TabbedPane.selected", Color.RED);
        //SwingUtilities.updateComponentTreeUI (tpUserGUI);
        
        //need to clean later. move to a function and use chetan's query
        List myList = new ArrayList();
        myList.add("harry potter");
        myList.add("ron weasly");
        myList.add("luna lovejoy");
        cbEnteredBy.removeAllItems();
        cbEnteredBy.addItem("Select Name");
        for (Object obj : myList)
        {
            cbEnteredBy.addItem(obj);
        }
        
        //remove later. this field will be set in project UI
        //setProjectID("4");
        lProjectName.setText(projectName);
    }
    
    public UserGUI(ProjectDetailsTable project) {
        initComponents();
        //this();
        controller = new Controller();
        projectObj = new ProjectDetailsTable();
        projectObj = project;
        System.out.println("-->" + projectObj.getProjectId());

    }
    
        
    public void setItemBudgetNameTextField (String s){
    	tfItemName.setText(s);
    }
    
    public void setDescriptionBudgetTextField (String s){
    	tfDescription.setText(s);
    }
    
    public void setEstimatedBudgetTextField (String s){
    	tfEstimatedCost.setText(s);
    }
    
    public void setActualBudgetTextField (String s){
    	tfActualCost.setText(s);
    }
    
    public void setItemSelectedBudgetID (String s) {
        itemSelectedBudgetID = Integer.parseInt(s);
    }
    
    public void setProjectID (int i){
        //projectID = Integer.parseInt(s);
        projectID = i;
    }
    
    public int getProjectID() {
        return projectID;
    }
    
    public void setProjectTitle (String s){
        //lProjectName.setText(s);
        projectName = s;
    }
    
    public void setNotesTextArea (String s){
        tfNotes.setText(s);
    }
    
    public void setTimestampDateChooser (String s){
        try {
            if (s == "")
            {
                dcDate.setDate(null);
            }
            else
            {
                DateFormat sdff = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date frmDate = sdff.parse(s);
                dcDate.setDate(frmDate);
            }
        
        } catch(ParseException err) {
            err.toString();
	}
    }
    
    public void setEnteredByComboBox (String s){
        cbEnteredBy.setSelectedItem(s);
    }
    
    public void setContactNameTextField (String s){
        tfContactName.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pUserGUIBanner = new javax.swing.JPanel();
        lUserGUIBanner = new javax.swing.JLabel();
        pProjectName = new javax.swing.JPanel();
        lProjectName = new javax.swing.JLabel();
        lProjectHome = new javax.swing.JLabel();
        tpUserGUI = new javax.swing.JTabbedPane();
        pOverview = new javax.swing.JPanel();
        pTasks = new javax.swing.JPanel();
        spTasks = new javax.swing.JScrollPane();
        tTasks = new javax.swing.JTable();
        pCreateTask = new javax.swing.JPanel();
        lTaskName = new javax.swing.JLabel();
        tfTaskName = new javax.swing.JTextField();
        lDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jaDescription = new javax.swing.JTextArea();
        lAssignee = new javax.swing.JLabel();
        cbAssignee = new javax.swing.JComboBox();
        lParentTask = new javax.swing.JLabel();
        tfParentTask = new javax.swing.JTextField();
        lStartDate = new javax.swing.JLabel();
        lEndDate = new javax.swing.JLabel();
        dcStartDate = new com.toedter.calendar.JDateChooser();
        dcEndDate = new com.toedter.calendar.JDateChooser();
        lPercentDone = new javax.swing.JLabel();
        cbPercentDone = new javax.swing.JComboBox();
        bAddTask = new javax.swing.JButton();
        pBudget = new javax.swing.JPanel();
        lItemName = new javax.swing.JLabel();
        lItemDescription = new javax.swing.JLabel();
        lEstimatedCost = new javax.swing.JLabel();
        lActualCost = new javax.swing.JLabel();
        tfItemName = new javax.swing.JTextField();
        tfDescription = new javax.swing.JTextField();
        tfEstimatedCost = new javax.swing.JTextField();
        tfActualCost = new javax.swing.JTextField();
        bAddNewBudget = new javax.swing.JButton();
        bSaveChanges = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        pBudgetTable = new javax.swing.JPanel();
        pCommunications = new javax.swing.JPanel();
        lContactName = new javax.swing.JLabel();
        tfContactName = new javax.swing.JTextField();
        lDate = new javax.swing.JLabel();
        dcDate = new com.toedter.calendar.JDateChooser();
        lNotes = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfNotes = new javax.swing.JTextArea();
        lEnteredBy = new javax.swing.JLabel();
        cbEnteredBy = new javax.swing.JComboBox();
        bAddCommunications = new javax.swing.JButton();
        bResetCommunicationsFields = new javax.swing.JButton();
        pCommunicationsTable = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1248, 600));

        pUserGUIBanner.setBackground(new java.awt.Color(255, 255, 255));
        pUserGUIBanner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 5));
        pUserGUIBanner.setPreferredSize(new java.awt.Dimension(1248, 95));

        lUserGUIBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fil-3squares-02.jpg"))); // NOI18N
        lUserGUIBanner.setPreferredSize(new java.awt.Dimension(1248, 80));

        javax.swing.GroupLayout pUserGUIBannerLayout = new javax.swing.GroupLayout(pUserGUIBanner);
        pUserGUIBanner.setLayout(pUserGUIBannerLayout);
        pUserGUIBannerLayout.setHorizontalGroup(
            pUserGUIBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUserGUIBannerLayout.createSequentialGroup()
                .addComponent(lUserGUIBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pUserGUIBannerLayout.setVerticalGroup(
            pUserGUIBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUserGUIBannerLayout.createSequentialGroup()
                .addComponent(lUserGUIBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pProjectName.setBackground(new java.awt.Color(255, 255, 255));
        pProjectName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        pProjectName.setPreferredSize(new java.awt.Dimension(1248, 40));

        lProjectName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lProjectName.setForeground(new java.awt.Color(255, 102, 0));
        lProjectName.setText("Replace with project name");
        lProjectName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lProjectNameMouseClicked(evt);
            }
        });

        lProjectHome.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lProjectHome.setForeground(new java.awt.Color(255, 102, 0));
        lProjectHome.setText("Project Home   > ");
        lProjectHome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lProjectHomeFocusGained(evt);
            }
        });
        lProjectHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lProjectHomeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lProjectHomeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pProjectNameLayout = new javax.swing.GroupLayout(pProjectName);
        pProjectName.setLayout(pProjectNameLayout);
        pProjectNameLayout.setHorizontalGroup(
            pProjectNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProjectNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lProjectHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(722, Short.MAX_VALUE))
        );
        pProjectNameLayout.setVerticalGroup(
            pProjectNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProjectNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pProjectNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lProjectHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lProjectName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tpUserGUI.setBackground(new java.awt.Color(255, 255, 255));
        tpUserGUI.setPreferredSize(new java.awt.Dimension(1248, 850));

        pOverview.setBackground(new java.awt.Color(255, 255, 255));
        pOverview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        javax.swing.GroupLayout pOverviewLayout = new javax.swing.GroupLayout(pOverview);
        pOverview.setLayout(pOverviewLayout);
        pOverviewLayout.setHorizontalGroup(
            pOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1223, Short.MAX_VALUE)
        );
        pOverviewLayout.setVerticalGroup(
            pOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        tpUserGUI.addTab("Overview", pOverview);

        pTasks.setBackground(new java.awt.Color(255, 255, 255));
        pTasks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        spTasks.setPreferredSize(new java.awt.Dimension(900, 304));

        tTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Task", "% Done", "Assignee", "Start Date", "End Date"
            }
        ));
        spTasks.setViewportView(tTasks);

        javax.swing.GroupLayout pTasksLayout = new javax.swing.GroupLayout(pTasks);
        pTasks.setLayout(pTasksLayout);
        pTasksLayout.setHorizontalGroup(
            pTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTasksLayout.createSequentialGroup()
                .addComponent(spTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 323, Short.MAX_VALUE))
        );
        pTasksLayout.setVerticalGroup(
            pTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTasksLayout.createSequentialGroup()
                .addComponent(spTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tpUserGUI.addTab("Tasks", pTasks);

        pCreateTask.setBackground(new java.awt.Color(255, 255, 255));
        pCreateTask.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        lTaskName.setText("Task Name");

        lDescription.setText("Description");

        jaDescription.setColumns(20);
        jaDescription.setRows(5);
        jScrollPane1.setViewportView(jaDescription);

        lAssignee.setText("Assignee");

        cbAssignee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lParentTask.setText("Parent Task");

        lStartDate.setText("Start Date");

        lEndDate.setText("End Date");

        lPercentDone.setText("% Done");

        cbPercentDone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 %", "10%", "25 %", "50 %", "75 %", "90 %", "100 %" }));

        bAddTask.setBackground(new java.awt.Color(255, 51, 0));
        bAddTask.setText("Add Task");
        bAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCreateTaskLayout = new javax.swing.GroupLayout(pCreateTask);
        pCreateTask.setLayout(pCreateTaskLayout);
        pCreateTaskLayout.setHorizontalGroup(
            pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateTaskLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lParentTask)
                    .addComponent(lAssignee)
                    .addComponent(lDescription)
                    .addComponent(lTaskName)
                    .addComponent(lStartDate))
                .addGap(35, 35, 35)
                .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAddTask)
                    .addComponent(tfTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pCreateTaskLayout.createSequentialGroup()
                        .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfParentTask, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lEndDate)
                            .addComponent(lPercentDone))
                        .addGap(42, 42, 42)
                        .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPercentDone, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbAssignee, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        pCreateTaskLayout.setVerticalGroup(
            pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateTaskLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pCreateTaskLayout.createSequentialGroup()
                        .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTaskName)
                            .addComponent(tfTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDescription)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCreateTaskLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dcStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lStartDate)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCreateTaskLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lEndDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lParentTask)
                    .addComponent(tfParentTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPercentDone)
                    .addComponent(cbPercentDone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pCreateTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAssignee, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAssignee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(bAddTask)
                .addContainerGap())
        );

        tpUserGUI.addTab("Create Task", pCreateTask);

        pBudget.setBackground(new java.awt.Color(255, 255, 255));
        pBudget.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        pBudget.setPreferredSize(new java.awt.Dimension(1227, 1000));

        lItemName.setText("Item Name");

        lItemDescription.setText("Description");

        lEstimatedCost.setText("Estimated Cost");

        lActualCost.setText("Actual Cost");

        bAddNewBudget.setBackground(new java.awt.Color(255, 102, 0));
        bAddNewBudget.setText("Add New Budget");
        bAddNewBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddNewBudgetActionPerformed(evt);
            }
        });

        bSaveChanges.setText("Save Edits");
        bSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveChangesActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        pBudgetTable.setBackground(new java.awt.Color(255, 255, 255));
        pBudgetTable.setPreferredSize(new java.awt.Dimension(700, 120));
        pBudgetTable.setLayout(new javax.swing.BoxLayout(pBudgetTable, javax.swing.BoxLayout.X_AXIS));

        javax.swing.GroupLayout pBudgetLayout = new javax.swing.GroupLayout(pBudget);
        pBudget.setLayout(pBudgetLayout);
        pBudgetLayout.setHorizontalGroup(
            pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBudgetLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBudgetLayout.createSequentialGroup()
                        .addComponent(lEstimatedCost)
                        .addGap(18, 18, 18)
                        .addComponent(tfEstimatedCost, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBudgetLayout.createSequentialGroup()
                        .addGroup(pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pBudgetLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lItemDescription))
                            .addComponent(lItemName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addComponent(tfDescription)))
                    .addGroup(pBudgetLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lActualCost)
                        .addGap(18, 18, 18)
                        .addGroup(pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pBudgetLayout.createSequentialGroup()
                                .addComponent(bAddNewBudget)
                                .addGap(27, 27, 27)
                                .addComponent(bSaveChanges)
                                .addGap(31, 31, 31)
                                .addComponent(bDelete))
                            .addComponent(tfActualCost, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pBudgetTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        pBudgetLayout.setVerticalGroup(
            pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBudgetLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lItemName)
                    .addComponent(tfItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lItemDescription)
                    .addComponent(tfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEstimatedCost)
                    .addComponent(tfEstimatedCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lActualCost)
                    .addComponent(tfActualCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddNewBudget)
                    .addComponent(bSaveChanges)
                    .addComponent(bDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBudgetTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpUserGUI.addTab("Budget", pBudget);

        pCommunications.setBackground(new java.awt.Color(255, 255, 255));
        pCommunications.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        lContactName.setText("Contact's Name");

        lDate.setText("Date");

        lNotes.setText("Notes");

        tfNotes.setColumns(20);
        tfNotes.setRows(5);
        jScrollPane4.setViewportView(tfNotes);

        lEnteredBy.setText("Entered by");

        cbEnteredBy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbEnteredByMouseEntered(evt);
            }
        });

        bAddCommunications.setBackground(new java.awt.Color(255, 102, 0));
        bAddCommunications.setText("Add");
        bAddCommunications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddCommunicationsActionPerformed(evt);
            }
        });

        bResetCommunicationsFields.setText("Reset Fields");
        bResetCommunicationsFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetCommunicationsFieldsActionPerformed(evt);
            }
        });

        pCommunicationsTable.setBackground(new java.awt.Color(255, 255, 255));
        pCommunicationsTable.setPreferredSize(new java.awt.Dimension(600, 100));
        pCommunicationsTable.setLayout(new javax.swing.BoxLayout(pCommunicationsTable, javax.swing.BoxLayout.X_AXIS));

        javax.swing.GroupLayout pCommunicationsLayout = new javax.swing.GroupLayout(pCommunications);
        pCommunications.setLayout(pCommunicationsLayout);
        pCommunicationsLayout.setHorizontalGroup(
            pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCommunicationsLayout.createSequentialGroup()
                .addGroup(pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCommunicationsLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lEnteredBy)
                            .addComponent(lNotes)
                            .addComponent(lContactName)
                            .addComponent(lDate))
                        .addGap(62, 62, 62)
                        .addGroup(pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEnteredBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfContactName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pCommunicationsLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(bAddCommunications)
                        .addGap(18, 18, 18)
                        .addComponent(bResetCommunicationsFields))
                    .addGroup(pCommunicationsLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(pCommunicationsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        pCommunicationsLayout.setVerticalGroup(
            pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCommunicationsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lContactName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNotes)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEnteredBy)
                    .addComponent(cbEnteredBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pCommunicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddCommunications)
                    .addComponent(bResetCommunicationsFields))
                .addGap(18, 18, 18)
                .addComponent(pCommunicationsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpUserGUI.addTab("Communications", pCommunications);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pUserGUIBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpUserGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pUserGUIBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpUserGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddTaskActionPerformed
       // ProjectGUI gui = new ProjectGUI();

        Object[] array = new Object[8];

        array[0] = tfTaskName.getText();
        array[1] = jaDescription.getText();
        array[2] = dcStartDate.getDate().toString();
        array[3] = dcEndDate.getDate().toString();
        array[4] = tfParentTask.getText();
        array[5] = (String) cbPercentDone.getSelectedItem();
        array[6] = (String) cbAssignee.getSelectedItem();
        array[7] = projectObj;

        // ProjectDetailsTable ProjectDetailsTable;
        //tt.setProjectId();
        System.out.println(projectObj.getProjectId());
        controller.addTask(array);
        JOptionPane.showMessageDialog(null, "Task " + array[0] + " created");

    }//GEN-LAST:event_bAddTaskActionPerformed

    private void bAddNewBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddNewBudgetActionPerformed
        // TODO add your handling code here:
        Object[] array = new Object[jtableBudget.getColumnCount()];
        //array[0] = "4"; //hard coded for testing. erwin need to fix
        array[0] = projectObj;
    	array[1] = tfItemName.getText();
    	array[2] = tfDescription.getText();
    	array[3] = tfActualCost.getText();
    	array[4] = tfEstimatedCost.getText();
    	budgetTableController.addBudgetRow(array);
    	tfItemName.setText("");
    	tfDescription.setText("");
    	tfEstimatedCost.setText("");
    	tfActualCost.setText("");
    }//GEN-LAST:event_bAddNewBudgetActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        System.out.println("BudgetID of row selected: "+itemSelectedBudgetID);
    	int delItem = itemSelectedBudgetID;
    	budgetTableController.deleteRow(delItem);
    	tfItemName.setText("");
    	tfDescription.setText("");
    	tfEstimatedCost.setText("");
    	tfActualCost.setText("");
        
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveChangesActionPerformed
        // TODO add your handling code here:
        String[] array = new String[jtableBudget.getColumnCount()];  
        //array[0] = "4"; //hard coded for testing. erwin need to fix
        array[0] = String.valueOf(projectID);
    	array[1] = tfItemName.getText();
    	array[2] = tfDescription.getText();
    	array[3] = tfActualCost.getText();
    	array[4] = tfEstimatedCost.getText();
        array[5] = String.valueOf(itemSelectedBudgetID); 
        budgetTableController.updateRow(array);
        tfItemName.setText("");
    	tfDescription.setText("");
    	tfEstimatedCost.setText("");
    	tfActualCost.setText("");
      
    }//GEN-LAST:event_bSaveChangesActionPerformed

    private void bAddCommunicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddCommunicationsActionPerformed
        // TODO add your handling code here:
        Object[] array = new Object[jtableCommunications.getColumnCount()];
        Format formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String date = formatter.format(dcDate.getDate());
        array[1] = date;
    	array[2] = tfNotes.getText();
    	array[3] = (String)cbEnteredBy.getSelectedItem();
    	array[4] = tfContactName.getText();
        //array[5] = "4"; //hard coded. erwin need to fix
        array[5] = projectObj;
    	communicationsTableController.addCommunicationRow(array);
    	setTimestampDateChooser("");
        tfNotes.setText("");
        cbEnteredBy.setSelectedItem("Select Name");
        tfContactName.setText(""); 
    }//GEN-LAST:event_bAddCommunicationsActionPerformed

    private void bResetCommunicationsFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetCommunicationsFieldsActionPerformed
        // TODO add your handling code here:
        setTimestampDateChooser("");
        tfNotes.setText("");
        cbEnteredBy.setSelectedItem("Select Name");
        tfContactName.setText("");    
    }//GEN-LAST:event_bResetCommunicationsFieldsActionPerformed

    private void lProjectNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProjectNameMouseClicked
        // TODO add your handling code here:
        System.out.println("the label is clicked");
    }//GEN-LAST:event_lProjectNameMouseClicked

    private void lProjectHomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lProjectHomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lProjectHomeFocusGained

    private void lProjectHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProjectHomeMouseEntered
        // TODO add your handling code here:
        lProjectHome.setForeground(Color.blue);
    }//GEN-LAST:event_lProjectHomeMouseEntered

    private void lProjectHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lProjectHomeMouseExited
        // TODO add your handling code here:
        lProjectHome.setForeground(new Color(255,104,0));
    }//GEN-LAST:event_lProjectHomeMouseExited

    private void cbEnteredByMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbEnteredByMouseEntered
        // TODO add your handling code here:
        memberDetails = controller.retrieveAllMembers();
    }//GEN-LAST:event_cbEnteredByMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddCommunications;
    private javax.swing.JButton bAddNewBudget;
    private javax.swing.JButton bAddTask;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bResetCommunicationsFields;
    private javax.swing.JButton bSaveChanges;
    private javax.swing.JComboBox cbAssignee;
    private javax.swing.JComboBox cbEnteredBy;
    private javax.swing.JComboBox cbPercentDone;
    private com.toedter.calendar.JDateChooser dcDate;
    private com.toedter.calendar.JDateChooser dcEndDate;
    private com.toedter.calendar.JDateChooser dcStartDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jaDescription;
    private javax.swing.JLabel lActualCost;
    private javax.swing.JLabel lAssignee;
    private javax.swing.JLabel lContactName;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel lDescription;
    private javax.swing.JLabel lEndDate;
    private javax.swing.JLabel lEnteredBy;
    private javax.swing.JLabel lEstimatedCost;
    private javax.swing.JLabel lItemDescription;
    private javax.swing.JLabel lItemName;
    private javax.swing.JLabel lNotes;
    private javax.swing.JLabel lParentTask;
    private javax.swing.JLabel lPercentDone;
    private javax.swing.JLabel lProjectHome;
    private javax.swing.JLabel lProjectName;
    private javax.swing.JLabel lStartDate;
    private javax.swing.JLabel lTaskName;
    private javax.swing.JLabel lUserGUIBanner;
    private javax.swing.JPanel pBudget;
    private javax.swing.JPanel pBudgetTable;
    private javax.swing.JPanel pCommunications;
    private javax.swing.JPanel pCommunicationsTable;
    private javax.swing.JPanel pCreateTask;
    private javax.swing.JPanel pOverview;
    private javax.swing.JPanel pProjectName;
    private javax.swing.JPanel pTasks;
    private javax.swing.JPanel pUserGUIBanner;
    private javax.swing.JScrollPane spTasks;
    private javax.swing.JTable tTasks;
    private javax.swing.JTextField tfActualCost;
    private javax.swing.JTextField tfContactName;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfEstimatedCost;
    private javax.swing.JTextField tfItemName;
    private javax.swing.JTextArea tfNotes;
    private javax.swing.JTextField tfParentTask;
    private javax.swing.JTextField tfTaskName;
    private javax.swing.JTabbedPane tpUserGUI;
    // End of variables declaration//GEN-END:variables
}
